# Repository settings for branch protection and other configurations
# This file is used by the Probot Settings app: https://probot.github.io/apps/settings/
# To use this, install the Settings app on your repository

repository:
  # Repository description
  description: "A small script to upload a markdown file as confluence page"
  
  # Repository homepage
  homepage: https://github.com/jfheinrich/confluence-markdown-uploader
  
  # Repository topics for better discoverability
  topics:
    - confluence
    - markdown
    - shell-script
    - posix
    - automation
    - devops
  
  # Enable/disable features
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  
  # Enable automated security fixes and vulnerability alerts
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  
  # Merge strategy settings
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true
  
  # Default values for squash commits
  squash_merge_commit_title: "PR_TITLE"
  squash_merge_commit_message: "PR_BODY"

# Branch protection rules
branches:
  - name: main
    # Branch protection settings following best practices
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        # Require at least one approval
        required_approving_review_count: 1
        # Dismiss stale reviews when new commits are pushed
        dismiss_stale_reviews: true
        # Require review from code owners (defined in CODEOWNERS file)
        require_code_owner_reviews: true
        # Prevent authors from approving their own PRs - require approval from someone else after the latest push
        require_last_push_approval: true
      
      # Require status checks to pass before merging
      required_status_checks:
        # Require branches to be up to date before merging
        strict: true
        # List of required status checks (will be populated when workflows are added)
        checks:
          - context: "ShellCheck Analysis"
          - context: "POSIX Shell Compliance"
      
      # Enforce all configured restrictions for administrators
      enforce_admins: true
      
      # Prevent force pushes to protected branch
      allow_force_pushes: false
      
      # Prevent deletion of protected branch
      allow_deletions: false
      
      # Require linear history (no merge commits, use rebase or squash)
      required_linear_history: true
      
      # Require conversation resolution before merging
      required_conversation_resolution: true
      
      # Lock branch (prevent all pushes)
      lock_branch: false
      
      # Allow fork syncing
      allow_fork_syncing: true
      
      # Restrictions on who can push to the branch
      restrictions: null

# Labels for issues and pull requests
labels:
  # Type labels
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  
  - name: "security"
    color: "ee0701"
    description: "Security-related issues or improvements"
  
  # Priority labels
  - name: "priority: high"
    color: "b60205"
    description: "High priority issue"
  
  - name: "priority: medium"
    color: "fbca04"
    description: "Medium priority issue"
  
  - name: "priority: low"
    color: "0e8a16"
    description: "Low priority issue"
  
  # Status labels
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  
  - name: "invalid"
    color: "e4e669"
    description: "This doesn't seem right"
  
  # Component labels
  - name: "shell-script"
    color: "1d76db"
    description: "Related to shell script implementation"
  
  - name: "ci/cd"
    color: "28a745"
    description: "Related to CI/CD workflows"
  
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"
