# Repository settings for branch protection and other configurations
# This file is used by the Probot Settings app: https://probot.github.io/apps/settings/
# To use this, install the Settings app on your repository

repository:
  # Repository description
  description: "A small script to upload a markdown file as confluence page"
  
  # Repository homepage
  homepage: https://github.com/jfheinrich/confluence-markdown-uploader
  
  # Enable/disable features
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  
  # Enable automated security fixes
  allow_auto_merge: false
  delete_branch_on_merge: true

# Branch protection rules
branches:
  - name: main
    # Branch protection settings following best practices
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        # Require at least one approval
        required_approving_review_count: 1
        # Dismiss stale reviews when new commits are pushed
        dismiss_stale_reviews: true
        # Require review from code owners (defined in CODEOWNERS file)
        require_code_owner_reviews: true
        # Prevent authors from approving their own PRs
        require_last_push_approval: false
      
      # Require status checks to pass before merging
      required_status_checks:
        # Require branches to be up to date before merging
        strict: true
        # List of required status checks (will be populated when workflows are added)
        checks:
          - context: "ShellCheck Analysis"
          - context: "POSIX Shell Compliance"
      
      # Enforce all configured restrictions for administrators
      enforce_admins: true
      
      # Prevent force pushes to protected branch
      allow_force_pushes: false
      
      # Prevent deletion of protected branch
      allow_deletions: false
      
      # Require linear history (no merge commits, use rebase or squash)
      required_linear_history: true
      
      # Require conversation resolution before merging
      required_conversation_resolution: true
      
      # Lock branch (prevent all pushes)
      lock_branch: false
      
      # Allow fork syncing
      allow_fork_syncing: true
      
      # Restrictions on who can push to the branch
      restrictions: null
